<?php
namespace maxcom\user\components;
use yii\base\Component;

class User extends \yii\web\User {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    
}